version: "3.9"

services:
  windapi:
    build:
      context: .
      args:
        - "DEV=true"
    ports:
      - "8000:8000"
    volumes:
      - ./windapi:/windapi
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"