# Generated by Django 3.2.25 on 2024-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_assessments', '0002_auto_20240919_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windassessment',
            name='turbine',
        ),
        migrations.AddField(
            model_name='windassessment',
            name='turbine_type',
            field=models.CharField(choices=[('turbine_model_a', 'Turbine Model A'), ('turbine_model_b', 'Turbine Model B')], default='turbine_model_a', max_length=20),
        ),
    ]
