# Generated by Django 3.2.25 on 2024-09-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_assessments', '0003_auto_20240920_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windassessment',
            name='report_type',
            field=models.CharField(choices=[('feasibility', 'Feasibility Assessment'), ('wind_resource', 'Wind Resource Assessment'), ('site_suitability', 'Site Suitability Assessment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='windassessment',
            name='turbine_type',
            field=models.CharField(choices=[('turbine_model_a', 'Turbine Model A'), ('turbine_model_b', 'Turbine Model B')], max_length=20),
        ),
    ]
